name: 🔑 Solicitar Adição de Membro
description: Solicitar a inclusão de um novo membro na organização
title: "[ADD] "
labels: ["adicionar-membro", "em-análise"]
body:
  - type: markdown
    attributes:
      value: |
        Preencha as informações abaixo para solicitar a inclusão de um novo membro.
        
  - type: input
    id: github-username
    attributes:
      label: Username do GitHub
      description: Digite o username do GitHub do novo membro
      placeholder: ex. octocat
    validations:
      required: true
      
  - type: input
    id: discord-username
    attributes:
      label: Username do Discord
      description: Digite o username do Discord do novo membro
      placeholder: ex. usuario
    validations:
      required: true
      
  - type: dropdown
    id: project
    attributes:
      label: Projeto
      description: Selecione o projeto ao qual o membro será vinculado
      options:
        - NextStep
        - Nucleo 42 (Plataforma web)
    validations:
      required: true
      
- type: dropdown
  id: role
  attributes:
    label: Função/Papel
    description: Selecione qual será o papel/função do membro no projeto
    options:
      - Analista de Dados
      - Cientista de Dados
      - Desenvolvedor Back-end
      - Desenvolvedor Front-end
      - Desenvolvedor Mobile Android
      - Desenvolvedor Mobile iOS
      - Desenvolvedor Mobile (multiplataforma)
      - Engenheiro de Dados
      - UI/UX Designer
    validations:
      required: true
